### ISSUE TITLE
There is a problem with your colour mapping configuration.

### ISSUE THREAD

**Issue by JP3251** [phw198/OutlookGoogleCalendarSync#1539]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.1
**Edition**: Portable  
**Sync Direction**:  O<->G
![2022-09-26_09h15_25](https://user-images.githubusercontent.com/48731166/192287603-3c64bf76-9fdb-46e4-81ae-7e546ada7788.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9646526/OGcalsync.log)

**Bug Description**  
When outlook google calendar sync starts first time it says there's a problem with colour mapping configuration.  However, color mapping config is not turned on

**Steps to Reproduce the Issue**  
1. Turn on computer

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.9.5.15](https://github.com/phw198/OutlookGoogleCalendarSync/files/10096479/v2.9.5.15.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by JP3251** [comment]
Hi,  Colours/categories mapping is unchecked.  and I still get the same error with the hotfix applied
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10155908/OGcalsync.log)

**Comment by phw198** [comment]
Hi @JP3251 

From your log file it looks like Profile "GOOGLE TO NORR" has the colours set to sync under the "What" section in settings. So with that in mind, I think OGCS is working as expected. If you turn that off without fixing the mappings, it should no longer complain.
