### ISSUE TITLE
Not handling COM error properly: [0x8001010A] RPC_E_SERVERCALL_RETRYLATER

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#2165]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v3.0.0.16  
**Edition**: Portable  
**Sync Direction**: N/A

**Bug Description**  
When OGCS attempts to start an instance of Outlook because one isn't already running, it does not automatically retry when a COM error `0x8001010A` is returned.

Full error is `Creating an instance of the COM component with CLSID {0006F03A-0000-0000-C000-000000000046} from the IClassFactory failed due to the following error: 8001010a The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER)).`

**Any other information**  
Any additional information that may help troubleshoot the issue.  
```
2025-08-07 15:10:55,814 WARN  6  OutlookGoogleCalendarSync.Outlook.Calendar [1169] -  No Outlook process available to attach to.
2025-08-07 15:10:55,816 INFO  6  OutlookGoogleCalendarSync.Outlook.Calendar [1202] -  Starting a new instance of Outlook.
2025-08-07 15:10:56,496 WARN  6  OutlookGoogleCalendarSync.Outlook.Errors [33] -  [0x8001010A] >> Creating an instance of the COM component with CLSID {0006F03A-0000-0000-C000-000000000046} from the IClassFactory failed due to the following error: 8001010a The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER)).
2025-08-07 15:10:56,497 DEBUG 6  OutlookGoogleCalendarSync.Telemetry [202] -  GA4: {"client_id":"5eada93fac5a89faecb359e9e27df680","user_id":"5eada93fac5a89faecb359e9e27df680","non_personalized_ads":true,"user_properties":{"ogcs_version":{"value":"3.0.0.16"},"benefactor":{"value":"True"},"account_present":{"value":"True"},"profiles":{"value":"1"},"outlook_version":{"value":null},"outlook_name":{"value":null},"continent":{"value":null},"country":{"value":null},"country_code":{"value":null},"region":{"value":null},"city":{"value":null}},"events":[{"name":"ogcs_error","params":{"engagement_time_msec":1,"com_object":"0x8001010A","sync_count":105}}]}
2025-08-07 15:10:57,962 DEBUG 6  OutlookGoogleCalendarSync.Outlook.Calendar [1354] -  Could not find the COM error 0x8001010A in the wiki.
2025-08-07 15:10:57,962 WARN  6  OutlookGoogleCalendarSync.Outlook.Calendar [1367] -  Did not find COM error in Wiki, so now checking for hard-coded URLs.
2025-08-07 15:10:57,962 WARN  6  OutlookGoogleCalendarSync.Exception [19] -  COM error not in wiki.
2025-08-07 15:10:57,963 WARN  6  OutlookGoogleCalendarSync.Outlook.Errors [33] -  [0x8001010A] >> Creating an instance of the COM component with CLSID {0006F03A-0000-0000-C000-000000000046} from the IClassFactory failed due to the following error: 8001010a The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER)).
2025-08-07 15:10:57,964 ERROR 6  OutlookGoogleCalendarSync.Exception [35] -  System.Runtime.InteropServices.COMException: Creating an instance of the COM component with CLSID {0006F03A-0000-0000-C000-000000000046} from the IClassFactory failed due to the following error: 8001010a The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER)).
2025-08-07 15:10:57,965 ERROR 6  OutlookGoogleCalendarSync.Exception [22] -  Code: 0x8001010A,-2147417846; Location: PoorlyOfficeInstall() in PoorlyOfficeInstall() at offset 28 in OutlookCalendar.cs:1239:17
2025-08-07 15:10:57,966 WARN  6  OutlookGoogleCalendarSync.Outlook.Errors [33] -  [0x80131600] >> COM error 0x8001010A encountered.
Please check if there is a published solution on the OGCS wiki.
2025-08-07 15:10:57,966 ERROR 6  OutlookGoogleCalendarSync.Exception [35] -  System.ApplicationException: COM error 0x8001010A encountered.
Please check if there is a published solution on the OGCS wiki.
2025-08-07 15:10:57,966 ERROR 6  OutlookGoogleCalendarSync.Exception [22] -  Code: 0x80131600,-2146232832; Location: PoorlyOfficeInstall() in PoorlyOfficeInstall() at offset 547 in OutlookCalendar.cs:1267:21
2025-08-07 15:10:57,967 ERROR 6  OutlookGoogleCalendarSync.Exception [66] -     at OutlookGoogleCalendarSync.Outlook.Calendar.PoorlyOfficeInstall(Exception caughtException) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 1267
   at OutlookGoogleCalendarSync.Outlook.Calendar.openOutlook(Application& oApp, Boolean withSystemCall) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 1230
   at OutlookGoogleCalendarSync.Outlook.Calendar.openOutlookHandler(Application& oApp, Boolean withSystemCall) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 1195
   at OutlookGoogleCalendarSync.Outlook.Calendar.AttachToOutlook(Application& oApp, Boolean openOutlookOnFail, Boolean withSystemCall) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 1169
   at OutlookGoogleCalendarSync.Outlook.OutlookNew.Connect() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook.Factory\OutlookNew.cs:line 26
   at OutlookGoogleCalendarSync.Outlook.Calendar.get_Instance() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 39
   at OutlookGoogleCalendarSync.Sync.Engine.CloudCalendar.Synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\CloudCalendar.cs:line 57
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.<>c__DisplayClass11_1.<StartSync>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 142
2025-08-07 15:10:57,967 ERROR 6  OutlookGoogleCalendarSync.Console [424] -  <Sync\Calendar.cs:173> COM error 0x8001010A encountered.
2025-08-07 15:10:57,967 ERROR 6  OutlookGoogleCalendarSync.Console [424] -  Please check if there is a published solution on the OGCS wiki.
2025-08-07 15:10:58,253 DEBUG 1  OutlookGoogleCalendarSync.Extensions.MessageBox [75] -  Sync Failed: The synchronisation failed - check the Sync tab for further details.
```

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v3.0.0.22.zip](https://github.com/user-attachments/files/21669966/v3.0.0.22.zip) (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `15B12ACA` Exe = `CD240472`

The log file should still show evidence of hitting `0x8001010A`, but OGCS should automatically retry a number of times before giving up if Outlook is still not responsive.

**Comment by MartinS-gxr** [comment]
I can confirm that the message still appears in the log but the interface is no longer popping up. Thanks a lot for the quick fix.
