### ISSUE TITLE
v3.0.0.30 O->G The specified time range is empty - midnight UTC issue

### ISSUE THREAD

**Issue by comrie** [phw198/OutlookGoogleCalendarSync#2194]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v3.0.0.30  
**Edition**: Installed  
**Sync Direction**: O->G

**Bug Description**  
Will not sync any appointment that ends at exactly 5:00 pm (this happens to be 00:00 UTC which is suspicious). If you change the appointment to end at 4:59 pm or 5:01 pm then it works fine. Starting time of the appointment does not matter, only the end time. Confirmed this by changing all the relevant appointments in various permutations (title, other attributes, start time, end time, appointments created by me, those created by others, etc.). It is definitely only the end time at 5pm. Also, it is all appointments ending at 5pm in the entire sync date range (not selective ones, so it is a consistent and reproducible issue).

**Steps to Reproduce the Issue**  
1. Start a sync (all goes as usual, checks and compares outlook and google calendars, updates appointments that have changed/are new.
2. As soon as it hits the first appointment ending at exactly 5:00 pm it pops up with an error and a box/button asking if I want to continue the sync or end it.
3. The error on the sync screen says:
9/19/2025 3:00 PM "Test Appointment "
New event failed to save.
The specified time range is empty. [400=BadRequest]

4. Note that the on-screen message only includes the start time of 3:00 pm (end time not provided in messages) but the end time issue is what my entire string of multiple errors (for all appointments ending at 5pm) like this have in common.

**Any other information**  
`OGcalsync.log` file attached

[OGcalsync.log](https://github.com/user-attachments/files/22448898/OGcalsync.log)

**Comment by jaylewis1970** [comment]
I have the same issue, and I confirmed there is a beginning and ending time 5 pm to 6 pm, but I still get:

**TRUNCATED**:

Sync version: 3.0.0.30

Profile: JAY

Sync started at 9/30/2025 7:53:14 AM

Syncing from 9/29/2025 to 11/30/2025

Outlook ↔ Google

Creating 2 Google calendar entries
11/15/2025 5:00 PM "Parks outdoor game in Charlotte"

New event failed to save.
The specified time range is empty. [400=BadRequest]

**Comment by phw198** [comment]
🔗 Other v3 timezone issues: #2197 #2148

**Comment by phw198** [comment]
:package: Apologies for the delay - ~~it should now be resolved with [hotfix v3.0.0.32.zip](https://github.com/user-attachments/files/23441653/v3.0.0.32.zip)~~ (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `CC22F747` Exe = `37C85053`

Please see #2237 for improved hotfix.

**Comment by girlinabillion** [comment]
Moving my comments over to this existing thread, (from the duplicate thread I created #2230 )

I just went ahead and applied hotfix v.3.0.0.32 from this thread and still experiencing issues. The error has gone away, but the events are not importing with the modified dates/times, but instead importing with the original recurring event's dates/times.

Steps I took after installing the hotfix:
I first did a sync and confirmed that the error did not return. But since I had already modified the destination calendar events to the correct times, I decided to do some double checking.

I deleted the recurring events off of the destination calendar, then did a new sync. The calendar events were added with their original dates/times, not their modified dates/times.

[OGcalsync.log](https://github.com/user-attachments/files/23616698/OGcalsync.log)

The specific recurring event I'm looking at is from Outlook. Today, the event should have been put as 3:30pm, and next Tue Nov 25, it should be 11am. The events are coming through at 10:30am, which is the original recurring event time.

ORIGINAL POST FROM DUPLICATE ISSUE that I created:

> OGCS Version: v3.0.0.30 Edition: Installed Sync Direction: G->O / O->G (I have one profile going one direction and a second profile going the other)
> 
> I'm having the same issue as [#2185](https://github.com/phw198/OutlookGoogleCalendarSync/issues/2185) did in version 2, in both directions. Whenever a recurring event has one of its events changed, or make changes on "this event and all following" I get either "The specified time range is empty. 400=bad request" (this was from Outlook to Google) or I get the Start Time is invalid because it's after the end time error (Google to Outlook).
> 
> Some of these are meeting invites that I didn't create, so I'm not able to delete them and recreate them, or make other edits to them. I was able to delete the Google events and recreate those, and the error resolved, until a change is made to one or more of the events in the series.
> 
> I've tried searching the issues, but I'm only seeing this reported on version 2 - apologies if there's already a duplicate.
> 
> Attaching logs - 11-01-2025 has a Google to Outlook error and current one has Outlook to Google error.
> 
> Thanks!
> 
> [OGcalsync_2025-11-01.log](https://github.com/user-attachments/files/23611538/OGcalsync_2025-11-01.log) [OGcalsync.log](https://github.com/user-attachments/files/23611520/OGcalsync.log)

**Comment by digitalplace** [comment]
I just applied the patch and it seems to be working for me.  Thank you for the quick response!

**Comment by phw198** [comment]
Please be aware the fix posted above is not quite correct and has been superseded by the fix in #2237.

**Comment by phw198** [comment]
I've released the fix on #2237 into v3.0.0.35 - the final release candidate for v3.0.1.
