### ISSUE TITLE
v3: Sync failure in v3.0.0.30 due to tzone://Microsoft/Utc

### ISSUE THREAD

**Issue by SamuelStevenson** [phw198/OutlookGoogleCalendarSync#2197]
**OGCS Version**: v3.0.0.3 
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I'm getting the following error in the Sync tab:

```
Creating 1 Google calendar entries
2025-09-25 10:00 AM "Office Hours"

2025-09-25 10:00 AM "Office Hours"
Event creation failed.
Time zone with ID tzone://Microsoft/Utc not found in source 2025b (mapping: $Revision$)
Parameter name: id
```

**Any other information**  
I notice in the log file that there is reference to a local folder on someone else's machine. Not sure if it's intentional:
C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\TimezoneDB

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/user-attachments/files/22519230/OGcalsync.log)

**Comment by phw198** [comment]
Interesting - looks to be very similar to #2148, though yours is actually referencing UTC, so the [hotfix posted there](https://github.com/phw198/OutlookGoogleCalendarSync/issues/2148#issuecomment-3240251606) might actually work correctly for you. Let me know if it does!

**Comment by SamuelStevenson** [comment]
Unfortunately, this doesn't seem to have worked. I'm still getting the
following error:
[image: image.png]

**Comment by phw198** [comment]
You mean you applied hotfix 3.0.0.31 and the events still fail to create, or the UTC timezone isn't correct when it created?

:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files. If you could include the log file too, that helps.

**Comment by SamuelStevenson** [comment]
Sorry, maybe this should be added as a new issue. I was thinking that they stemmed from the same thing.

The error I'm getting when attempting to sync this event is: New event failed to save. The specified time range is empty. [400=BadRequest]

Here is that section of the log file:
```
2025-11-13 09:11:28,749 INFO  6  OutlookGoogleCalendarSync.Console [428] -  <Sync\CloudCalendar.cs:208> Creating 1 Google calendar entries
2025-11-13 09:11:28,809 DEBUG 6  OutlookGoogleCalendarSync.Google.Graph.Calendar [555] -  Processing >> 2025-11-13 3:00 PM => "Creating academic calendar in Notion"
2025-11-13 09:11:28,812 DEBUG 6  OutlookGoogleCalendarSync.Console [426] -  <Google.Graph\GoogleCalendar.cs:555> 2025-11-13 3:00 PM "Creating academic calendar in Notion"
2025-11-13 09:11:28,987 DEBUG 6  OutlookGoogleCalendarSync.Google.CustomProperty [347] -  2025-11-13 3:00 PM => "Creating academic calendar in Notion"
2025-11-13 09:11:28,991 DEBUG 6  OutlookGoogleCalendarSync.Google.CustomProperty [347] -  outlook_CalendarID=AAMkAGIzNTc3ZjZmLTQ5N2YtNGMzOC1iNjY0LTg5NGNhNTU4MzJkZABGAAAAAAAHRsUoKsUPR6PrPtETJJ0sBwA9NJTKOt98RaSK9sVJm3prAAAAAAEGAAA9NJTKOt98RaSK9sVJm3prAAEdlZ9QAAA=
2025-11-13 09:11:28,993 DEBUG 6  OutlookGoogleCalendarSync.Google.CustomProperty [347] -  outlook_EntryID=AAMkAGIzNTc3ZjZmLTQ5N2YtNGMzOC1iNjY0LTg5NGNhNTU4MzJkZABGAAAAAAAHRsUoKsUPR6PrPtETJJ0sBwA9NJTKOt98RaSK9sVJm3prAAAAAAENAAA9NJTKOt98RaSK9sVJm3prAAdvXp5YAAA=
2025-11-13 09:11:28,994 DEBUG 6  OutlookGoogleCalendarSync.Google.CustomProperty [347] -  outlook_GlobalApptID=040000008200E00074C5B7101A82E00800000000E5ABA3D9D750DC010000000000000000100000009BDA2D83D7F59C48B4B314B40DDD12BF
2025-11-13 09:11:29,005 DEBUG 6  OutlookGoogleCalendarSync.Google.Graph.Calendar [638] -  Saving timestamp when OGCS created event.
2025-11-13 09:11:29,399 FAIL  6  OutlookGoogleCalendarSync.Google.Calendar [2305] -  The service calendar has thrown an exception. HttpStatusCode is BadRequest. The specified time range is empty.
2025-11-13 09:11:29,401 DEBUG 6  OutlookGoogleCalendarSync.Telemetry [203] -  GA4: {"client_id":"add5068226402a5cfecba7a28d66e3c0","user_id":"add5068226402a5cfecba7a28d66e3c0","non_personalized_ads":true,"user_properties":{"ogcs_version":{"value":"3.0.0.31"},"benefactor":{"value":"True"},"account_present":{"value":"True"},"profiles":{"value":"1"},"outlook_version":{"value":null},"outlook_name":{"value":null},"continent":{"value":"North America"},"country":{"value":"Canada"},"country_code":{"value":"CA"},"region":{"value":"British Columbia"},"city":{"value":"Parksville"}},"events":[{"name":"ogcs_error","params":{"engagement_time_msec":1,"api_google_error":"The service calendar has thrown an exception. HttpStatusCode is BadRequest. The specified time range","code":400,"domain":"calendar","reason":"timeRangeEmpty","message":"The specified time range is empty."}}]}
2025-11-13 09:11:29,404 WARN  6  OutlookGoogleCalendarSync.Google.Calendar [2437] -  Unhandled API exception.
2025-11-13 09:11:29,452 ERROR 6  OutlookGoogleCalendarSync.Console [424] -  <Google.Graph\GoogleCalendar.cs:538> New event failed to save.
2025-11-13 09:11:29,914 ERROR 6  OutlookGoogleCalendarSync.Exception [35] -  Google.GoogleApiException: The service calendar has thrown an exception. HttpStatusCode is BadRequest. The specified time range is empty.
2025-11-13 09:11:30,208 ERROR 6  OutlookGoogleCalendarSync.Exception [22] -  Code: 0x80131500,-2146233088; Location: MoveNext() in createCalendarEntry_save() at offset 407 in GoogleCalendar.cs:658:75
2025-11-13 09:11:30,211 ERROR 6  OutlookGoogleCalendarSync.Exception [66] -     at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OutlookGoogleCalendarSync.Google.Graph.Calendar.createCalendarEntry_save(Event ev, Event ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Google.Graph\GoogleCalendar.cs:line 658
   at OutlookGoogleCalendarSync.Google.Graph.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Google.Graph\GoogleCalendar.cs:line 531
2025-11-13 09:11:30,216 DEBUG 6  OutlookGoogleCalendarSync.Extensions.MessageBox [75] -  Sync item failed: New Google event failed to save. Continue with synchronisation?
```

**Comment by phw198** [comment]
No, that is a separate issue and one that should be fixed on #2194 - though it's still awaiting confirmation from someone affected.

What version of OGCS are you currently running? Did you patch to v3.0.0.31 and did that fix the UTC issue you described in your opening post?

For the moment, could you [switch to v3.0.0.32](https://github.com/phw198/OutlookGoogleCalendarSync/issues/2194#issuecomment-3508672160) and confirm the fix for "The specified time range is empty"?

**Comment by SamuelStevenson** [comment]
I'm currently running the 3.0.0.35 alpha build and still having this (or a very similar) issue. Even with the Timezone DB updated to 2025c, the Microsoft-proprietary ID still fails to map.

Current Environment:

- OGCS Version: 3.0.0.35 (Alpha)
- Timezone DB: 2025c
- Sync Direction: Outlook ↔ Google
- Latest Log Snippet (2026-02-04):

```
ERROR 4 OutlookGoogleCalendarSync.Console - Event creation failed.
System.ArgumentException: Time zone with ID tzone://Microsoft/Utc not found in source 2025c (mapping: $Revision$)
Parameter name: id
Code: 0x80070057,-2147024809; Location: ForId() in IANAtimezone() at offset 137 in TimezoneDB.cs:228:13
```

This happens consistently with third-party invites (like Calendly) that use this specific tzone:// URI. Is there any chance of adding this to the TimezoneDB.cs mapping in the next build?

**Comment by phw198** [comment]
@SamuelStevenson I was waiting for a response on [my post to you in November](https://github.com/phw198/OutlookGoogleCalendarSync/issues/2197#issuecomment-3538732471) last year. v3.0.0.35 doesn't have the work-in-progress hotfix in v3.0.0.31 because no one was engaging with either this issue or #2148, so it's not progressed.

:package: I've brought in the change from #2148 and applied over the top of v3.0.0.35 - please give [hotfix v3.0.0.36.zip](https://github.com/user-attachments/files/25154229/v3.0.0.36.zip) a go (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `B1FA0562` Exe = `F4FE67BD`

Let me know how it goes!

**Comment by RoyAc6** [comment]
@phw198 I've applied the v3.0.0.36 hotfix and confirmed that it is running, but I still have the same issue.

**Comment by phw198** [comment]
:package: Apologies, seems I didn't tweak the fix specifically for this UTC time zone when I created that hotfix 😖 Please try again with [hotfix v3.0.0.37.zip](https://github.com/user-attachments/files/25161992/v3.0.0.37.zip) (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `F8072FB4` Exe = `3248A01D`

Please let me know how it goes.

**Comment by RoyAc6** [comment]
@phw198 I confirm that v3.0.0.37 fixed it, thanks !

**Comment by SamuelStevenson** [comment]
v3.0.0.37 fixed it! Thanks Paul!!
