### ISSUE TITLE
remember which appointments are not for deletion

### ISSUE THREAD

**Issue by jlrose13** [phw198/OutlookGoogleCalendarSync#419]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.5  
**Installed or Portable**: Installed

**Problem Description**  
OGCS tends to determine that certain original appointments ought to be deleted.  Until this is resolved, I have deletions set to confirm.

**Steps to Reproduce the Issue**  
routing sync .  Same calendar items are tagged for deletion on every sync.  logs attached

**Any other information**  
perhaps add a feature that once a calendar item is tagged for deletion, and the user selects do not delete, that selections is remembered and the appointment no longer appears on future syncs and targeted for deletion.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1583453/OGcalsync.log)

**Comment by phw198** [comment]
As you've noted, the root cause that you're really getting at is the incorrect prompt for the deletion in the first place. I believe what may have caused this in the first place should be fixed by v2.6.5, so we just need to correct the legacy reason OGCS wants to delete `3/9/2018 10:30 AM  "HTM Feed Forward Session"`.

1. When you're sure Google has no changes that need syncing to Outlook
1. Set OGCS to one-way sync Outlook to Google.
1. Force a full sync by shift-clicking the `Sync` button
1. Set OGCS back to two-way sync.
1. Problem should be resolved.

Let me know...

**Comment by jlrose13** [comment]
I just went ahead and let ogcs delete and recreated the meeting.  Bit I tried the method you cite below in the past and did not resolve.  That was most likely with older versions.  I will try if the situation occurs again.

Thanks
Jim

**Comment by mshayne** [comment]
Your instructions worked well for me.  I had been using the program with no issues, until a couple of days ago (currently running 2.6.0.0).  I had not synced for a couple of months.  When I did, It deleted about 50 events in Outlook.  All of these had been advanced in my Outlook calendar from October to this week.  I think perhaps they fell outside of the 60-day range I had set and were therefore flagged for deletion, but that's just a guess.  I changed the settings to notify on delete and was able to prevent them from deleting, but it repeated this every time it synced.  I followed your instructions above and solved the problem.  Thanks!

**Comment by nz5fyr** [comment]
I have cases where the meeting organizer deletes all instances of the meeting, past and future, and I need to keep a history of my past meetings in Google to help with accounting for my time.  In this case, I am always prompted to delete the past meetings.  So in this case, it's not a bug fix, it's a use case/feature request.

**Comment by phw198** [comment]
@nz5fyr This should really be raised under a new enhancement request, but unfortunately it's not something I would be looking implement. As a workaround, you could either
* decline the cancelled/deleted series from the organiser and then set it to private, free and no reminder (so it doesn't block your work calendar, but still gets synced); or
* before the delete sync runs, go to Google calendar and "Copy To" the event to another "archive" calendar. Then display the standard Google calendar and the "archive" one to see your time accounting. If you miss the delete sync run, recover the item out the Google calendar Bin.
