### ISSUE TITLE
O->G: Missing Exceptions to Recurring Events

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#42]
I am trying to sync a meeting that has an original data of 03/03/2016 to
recurre every 3 weeks. The 05/05/2016 instance was moved to be on 05/10/2016.  
  
However, it is not showing up on the Google side. I have reproduced this issue
with v.2.2.0 and v.2.2.1.0. I have attempted a Forced Manual Sync (Shift-Sync
on v.2.2.1.0) as well as deleting the entire calendar on Google's side and
resync entirely (v.2.2.0 and v.2.2.1.0)  
  
Relevant portion of the log (as far as I can tell) on sync with v.2.2.1.0  

    
    
    2016-05-16 12:45:12,993 FINE 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - GetSummary - not all day event
    2016-05-16 12:45:12,993 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - 3/3/2016 1:00 PM (R) => "MEETING NAME"
    2016-05-16 12:45:13,008 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - This is a recurring appointment with 4 exceptions that will now be iteratively compared.
    2016-05-16 12:45:13,008 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 03/03/2016
    2016-05-16 12:45:13,008 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 24/03/2016
    2016-05-16 12:45:13,024 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 14/04/2016
    2016-05-16 12:45:13,024 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Finding Google instance for deleted Outlook exception:-
    2016-05-16 12:45:13,024 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] -   Original date: 05/05/2016
    2016-05-16 12:45:13,024 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Google exception event is not cached. Retrieving all recurring instances...
    2016-05-16 12:45:13,024 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all recurring event instances from Google.
    2016-05-16 12:45:13,450 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
    2016-05-16 12:45:13,876 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 2 received.
    2016-05-16 12:45:14,266 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 3 received.
    2016-05-16 12:45:14,501 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Matching Google Event recurrence found.
    2016-05-16 12:45:14,501 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - It is deleted in Google, so cannot compare items.
    
    <SNIP>
    
    2016-05-16 12:46:55,592 FINE 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - GetSummary - not all day event
    2016-05-16 12:46:55,592 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Processing >> 3/3/2016 1:00 PM (R) => "MEETING NAME"
    2016-05-16 12:46:55,592 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing Start time
    2016-05-16 12:46:55,592 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing End time
    2016-05-16 12:46:55,592 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Creating Google iCalendar definition for recurring event.
    2016-05-16 12:46:55,592 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Building RRULE
    2016-05-16 12:46:55,592 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Determining pattern for frequency olRecursWeekly.
    2016-05-16 12:46:55,592 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - WEEKLY
    2016-05-16 12:46:55,592 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - 3
    2016-05-16 12:46:55,592 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - RRULE:FREQ=WEEKLY;INTERVAL=3
    2016-05-16 12:46:55,608 FINE 5 OutlookGoogleCalendarSync.OutlookNew [0] - Timezone "(UTC-07:00) Mountain Time (US & Canada)" mapped to "America/Denver"
    2016-05-16 12:46:55,608 FINE 5 OutlookGoogleCalendarSync.OutlookNew [0] - Timezone "(UTC-07:00) Mountain Time (US & Canada)" mapped to "America/Denver"
    2016-05-16 12:46:55,608 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing Subject
    2016-05-16 12:46:55,624 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing Description
    2016-05-16 12:46:55,624 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing Location
    2016-05-16 12:46:55,624 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing Private
    2016-05-16 12:46:55,624 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing Free/Busy
    2016-05-16 12:46:55,624 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Comparing Reminder
    2016-05-16 12:46:55,624 FINE 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - GetSummary - not all day event
    2016-05-16 12:46:55,624 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - 3/3/2016 1:00 PM (R) => "MEETING NAME"
    2016-05-16 12:46:55,624 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - This is a recurring appointment with 4 exceptions that will now be iteratively compared.
    2016-05-16 12:46:55,639 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 03/03/2016
    2016-05-16 12:46:55,639 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 24/03/2016
    2016-05-16 12:46:55,639 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 14/04/2016
    2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Finding Google instance for deleted Outlook exception:-
    2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] -   Original date: 05/05/2016
    2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Google exception event is not cached. Retrieving all recurring instances...
    2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all recurring event instances from Google.
    2016-05-16 12:46:56,047 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
    2016-05-16 12:46:56,455 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 2 received.
    2016-05-16 12:46:57,134 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 3 received.
    2016-05-16 12:46:57,338 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Matching Google Event recurrence found.
    2016-05-16 12:46:57,338 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - It is deleted in Google, so cannot compare items.
    2016-05-16 12:46:57,338 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Doing a dummy update in order to update the last modified date of recurring event
    

Relevant portion of the log (as far as I can tell) on sync after deleting all
entries in Google calendar on v.2.2.1.0  

    
    
    2016-05-16 13:03:56,674 FINE 5 OutlookGoogleCalendarSync.MainForm [0] - Processing 29/141
    2016-05-16 13:03:56,678 FINE 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - GetSummary - not all day event
    2016-05-16 13:03:56,678 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Found a master Outlook recurring item outside sync date range: 3/3/2016 1:00 PM (R) => "MEETING NAME"
    2016-05-16 13:03:56,681 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all events from Google: 3/3/2016 -> 3/4/2016
    2016-05-16 13:03:57,266 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
    2016-05-16 13:03:57,266 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Looking for orphaned events to reclaim...
    2016-05-16 13:03:57,266 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - 0 unclaimed.
    2016-05-16 13:03:57,267 FINE 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - GetSummary - not all day event
    2016-05-16 13:03:57,268 WARN 5 OutlookGoogleCalendarSync.Recurrence [0] - Failed to find master Google event for: 3/3/2016 1:00 PM (R) => MEETING NAME"
    
    <SNIP>
    
    2016-05-16 13:16:19,915 FINE 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - GetSummary - not all day event
    2016-05-16 13:16:19,916 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Processing >> 3/3/2016 1:00 PM (R) => "MEETING NAME"
    2016-05-16 13:16:19,916 DEBUG 5 OutlookGoogleCalendarSync.MainForm [0] - 3/3/2016 1:00 PM (R) => "MEETING NAME"
    2016-05-16 13:16:19,920 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Creating Google iCalendar definition for recurring event.
    2016-05-16 13:16:19,922 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Building RRULE
    2016-05-16 13:16:19,923 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Determining pattern for frequency olRecursWeekly.
    2016-05-16 13:16:19,923 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - WEEKLY
    2016-05-16 13:16:19,923 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - 3
    2016-05-16 13:16:19,924 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - RRULE:FREQ=WEEKLY;INTERVAL=3
    2016-05-16 13:16:19,930 FINE 5 OutlookGoogleCalendarSync.OutlookNew [0] - Timezone "(UTC-07:00) Mountain Time (US & Canada)" mapped to "America/Denver"
    2016-05-16 13:16:19,977 FINE 5 OutlookGoogleCalendarSync.OutlookNew [0] - Timezone "(UTC-07:00) Mountain Time (US & Canada)" mapped to "America/Denver"
    2016-05-16 13:16:20,464 INFO 5 OutlookGoogleCalendarSync.MainForm [0] - This is a recurring item with some exceptions:-
    2016-05-16 13:16:20,464 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Creating Google recurrence exceptions.
    2016-05-16 13:16:20,464 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all recurring event instances from Google.
    2016-05-16 13:16:20,814 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
    2016-05-16 13:16:21,202 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 2 received.
    2016-05-16 13:16:21,581 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 3 received.
    2016-05-16 13:16:28,336 INFO 5 OutlookGoogleCalendarSync.MainForm [0] - Recurring exceptions completed.
    

Thanks for any help.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 268](http://outlookgooglecalendarsync.codeplex.com/workitem/268)
**Status:**	Resolved
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	May 19, 2016 at 9:28 PM
**Reported by:**	brozono
**Updated on:**	Aug 15, 2016 at 5:35 PM
**Updated by:**	brozono

#### Plaintext Attachments

[CodePlex Issue #268 Plain Text Attachments](https://gist.github.com/3ebd4e062ded4a7abbde7d4dffee22e4)

#### Binary Attachments

[OutlookGoogleCalendarSync.exe](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=268&FileAttachmentId=1588925)

**Comment by phw198** [comment]
On *2016-05-20 15:21:41 UTC*, **phw198** commented:

So I guess the question is, are you 100% sure that it was the recurrence on 5-May that was moved to 10--May. The log is clearly showing it as deleted in Outlook (and this is replicated "correctly" into Google):-
2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Finding Google instance for deleted Outlook exception:-
2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] -   Original date: 05/05/2016
2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Google exception event is not cached. Retrieving all recurring instances...
2016-05-16 12:46:55,655 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all recurring event instances from Google.
2016-05-16 12:46:56,047 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
2016-05-16 12:46:56,455 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 2 received.
2016-05-16 12:46:57,134 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 3 received.
2016-05-16 12:46:57,338 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Matching Google Event recurrence found.
2016-05-16 12:46:57,338 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - It is deleted in Google, so cannot compare items.
It's possible that Outlook is misreporting the item - sometimes it can cache changes, which causes odd behaviour. Could you:-

Close OGCS Close Outlook (make sure the system process has definitely ended) Delete the entire series in Google Open Outlook Open OGCS and sync

Any better?

**Comment by phw198** [comment]
On *2016-05-21 05:12:13 UTC*, **brozono** commented:

I followed the steps above. I verified that the Google entry was deleted by searching for it after deleting.

The exception for 05/05/2016 which was moved to 05/10/2016 and the exception for 05/26/2016 which had an updated location do not sync to Google.

Log for the first sync corresponding to the steps suggested is attached and issue for subsequent sync is pasted below:
2016-05-20 15:52:48,837 FINE 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - GetSummary - not all day event
2016-05-20 15:52:48,837 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - 3/3/2016 1:00 PM (R) => "MEETING NAME"
2016-05-20 15:52:48,840 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - This is a recurring appointment with 5 exceptions that will now be iteratively compared.
2016-05-20 15:52:48,867 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 03/03/2016
2016-05-20 15:52:48,875 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 24/03/2016
2016-05-20 15:52:48,882 FINE 5 OutlookGoogleCalendarSync.Recurrence [0] - Exception is deleted and outside date range being synced: 14/04/2016
2016-05-20 15:52:48,892 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Finding Google instance for deleted Outlook exception:-
2016-05-20 15:52:48,892 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] -   Original date: 05/05/2016
2016-05-20 15:52:48,892 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Google exception event is not cached. Retrieving all recurring instances...
2016-05-20 15:52:48,892 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all recurring event instances from Google.
2016-05-20 15:52:49,672 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
2016-05-20 15:52:50,197 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 2 received.
2016-05-20 15:52:50,762 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 3 received.
2016-05-20 15:52:51,044 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Matching Google Event recurrence found.
2016-05-20 15:52:51,044 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - It is deleted in Google, so cannot compare items.
2016-05-20 15:52:51,057 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Finding Google instance for deleted Outlook exception:-
2016-05-20 15:52:51,057 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] -   Original date: 26/05/2016
2016-05-20 15:52:51,164 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Google exception event is not cached. Retrieving all recurring instances...
2016-05-20 15:52:51,164 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all recurring event instances from Google.
2016-05-20 15:52:51,662 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
2016-05-20 15:52:52,169 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 2 received.
2016-05-20 15:52:52,649 DEBUG 5 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 3 received.
2016-05-20 15:52:52,944 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - Matching Google Event recurrence found.
2016-05-20 15:52:52,944 DEBUG 5 OutlookGoogleCalendarSync.Recurrence [0] - It is deleted in Google, so cannot compare items.
Also I have other examples of this and not just this specific meeting.

**Comment by phw198** [comment]
On *2016-05-21 05:13:35 UTC*, **brozono** commented:

With attachement

**Comment by phw198** [comment]
On *2016-05-26 23:15:50 UTC*, **brozono** commented:

After doing some debug I think I know what the issue is, but not clear to me what to do. I have created a new calendar and put a couple of new appointments in it and copied over one of the meetings that is posing the problem. This is the same mentioned
 above. I have cleared out a Google Calendar and when I do the first sync I get this.
2016-05-26 09:53:45,665 INFO 9 OutlookGoogleCalendarSync.MainForm [1013] - Creating 1 Google calendar entries...
2016-05-26 09:53:45,665 FINE 9 OutlookGoogleCalendarSync.OutlookCalendar [788] - GetSummary - not all day event
2016-05-26 09:53:45,665 DEBUG 9 OutlookGoogleCalendarSync.GoogleCalendar [311] - Processing >> 3/3/2016 1:00 PM (R) => "MEETING NAME"
2016-05-26 09:53:45,665 DEBUG 9 OutlookGoogleCalendarSync.MainForm [1012] - 3/3/2016 1:00 PM (R) => "MEETING NAME"
2016-05-26 09:53:45,665 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [33] - Creating Google iCalendar definition for recurring event.
2016-05-26 09:53:45,665 FINE 9 OutlookGoogleCalendarSync.Recurrence [177] - Building RRULE
2016-05-26 09:53:45,681 FINE 9 OutlookGoogleCalendarSync.Recurrence [180] - Determining pattern for frequency olRecursWeekly.
2016-05-26 09:53:45,681 FINE 9 OutlookGoogleCalendarSync.Recurrence [268] - WEEKLY
2016-05-26 09:53:45,681 FINE 9 OutlookGoogleCalendarSync.Recurrence [268] - 3
2016-05-26 09:53:45,681 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [37] - RRULE:FREQ=WEEKLY;INTERVAL=3
2016-05-26 09:53:45,743 FINE 9 OutlookGoogleCalendarSync.OutlookNew [306] - Timezone "(UTC-07:00) Mountain Time (US & Canada)" mapped to "America/Denver"
2016-05-26 09:53:45,759 FINE 9 OutlookGoogleCalendarSync.OutlookNew [306] - Timezone "(UTC-07:00) Mountain Time (US & Canada)" mapped to "America/Denve
Now I have added some logging into the CreateGoogleExceptions Function. And what I'm seeing is that all the exceptions for the given AppointmentItem are Deleted (exceptionIsDeleted is returning true)
2016-05-26 09:53:47,053 INFO 9 OutlookGoogleCalendarSync.MainForm [1013] - This is a recurring item with some exceptions:-
2016-05-26 09:53:47,053 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [426] - Creating Google recurrence exceptions.
2016-05-26 09:53:57,087 DEBUG 9 OutlookGoogleCalendarSync.GoogleCalendar [128] - Retrieving all recurring event instances from Google.
2016-05-26 09:53:57,950 DEBUG 9 OutlookGoogleCalendarSync.GoogleCalendar [137] - Page 1 received.
2016-05-26 09:53:58,452 DEBUG 9 OutlookGoogleCalendarSync.GoogleCalendar [137] - Page 2 received.
2016-05-26 09:53:59,048 DEBUG 9 OutlookGoogleCalendarSync.GoogleCalendar [137] - Page 3 received.
Added prints about the AppointmentItem
                log.Debug("AI Subject: " + ai.Subject.ToString());
                log.Debug("AI Recurring: " + ai.IsRecurring.ToString() );

2016-05-26 09:54:00,665 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [433] - AI Subject: MEETING NAME
2016-05-26 09:54:01,066 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [434] - AI Recurring: True
I'm looping over the exceptions and printing out the deleted and original date
                foreach (Microsoft.Office.Interop.Outlook.Exception oExcp in exps)
                {
                    Boolean isDeleted = exceptionIsDeleted(oExcp);
                    if (isDeleted)
                    {
                        exceptionDates.Add(oExcp.OriginalDate);
                        log.Debug("Found deleted exception once at " + oExcp.OriginalDate.ToString());
                    }
                }

2016-05-26 09:54:10,369 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [444] - Found deleted exception once at 3/3/2016 1:00:00 PM
2016-05-26 09:54:14,198 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [444] - Found deleted exception once at 3/24/2016 1:00:00 PM
2016-05-26 09:54:17,972 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [444] - Found deleted exception once at 4/14/2016 1:00:00 PM
2016-05-26 09:54:23,065 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [444] - Found deleted exception once at 5/5/2016 1:00:00 PM
2016-05-26 09:54:25,720 DEBUG 9 OutlookGoogleCalendarSync.Recurrence [444] - Found deleted exception once at 5/26/2016 1:00:00 PM
BUT the occurrence is in Outlook. I can see the exception! Of course sense the exception is deleted it doesn't have a valid AppointmentItem attached that you can reference.

If the exception is for something other than the data/time then I can find it this way
                    if (isDeleted) {
                        try {
                            exceptionOccurrence = ai.GetRecurrencePattern().GetOccurrence(oExcp.OriginalDate);
                            occurrenceFound = true;
                            exceptionStart = exceptionOccurrence.Start;                            
                            log.Debug("Occ Subject: " + exceptionOccurrence.Subject.ToString());
                            log.Debug("Occ Recurring: " + exceptionOccurrence.IsRecurring.ToString());
                            log.Debug("Occ Date: " + exceptionOccurrence.Start.ToString());                            
                        }
                        catch(System.Runtime.InteropServices.COMException)
                        {
                            log.Debug("Exception to " + ai.Subject + " at " + oExcp.OriginalDate.ToString() + " was not found!");
                        }
                    }
I can then use that to modify the Google event. However, if the meeting exception was because the meeting moved, then I can't find it. (Best idea I have is to search using GetOccurrence over the sync window specified in 15m increments, but this seems very brute
 force).

Is there another way to get the exceptions to recurrences because they are definitely there in Outlook itself, so the account isn't completely corrupted.

Thanks for any help!

**Comment by phw198** [comment]
On *2016-06-10 22:21:06 UTC*, **jhh09** commented:

I would just like to add that I too am experiencing this issue with 2.2.0. It caused me to miss an important meeting that had been re-scheduled, and now I am a bit uneasy about relying on this program to keep my calendar up to date. Not sure I can do much
 on the technical side to assist, but I don't mind helping with testing if needed.

**Comment by phw198** [comment]
On *2016-07-10 00:10:47 UTC*, **phw198** commented:

@brozono 
Thanks for the analysis - it clearly shows it's a caching issue. You may notice that the function exceptionIsDeleted() is a custom one to try and help with this problem. There is a debug logging line commented out in the function, which I think if you uncomment,
 will report that the exception appointment item is not accessible, but the exception itself is not a deletion.


I've restructured some of the COM object deferences - I think the attached v2.2.2.1 hotfix is behaving better, if you would like to give it a go and report back.

**Comment by phw198** [comment]
On *2016-07-20 03:43:58 UTC*, **brozono** commented:

This hotfix appears to fix the issue. I had a test calendar with the issue and I can see it properly syncing the 05-10-2016 exception now. See attached log.


I also tested with my main calendar and have reviewed 5 weeks of entries and this all looks correct.


Thanks for the fix. Can't wait to see it released.

**Comment by phw198** [comment]
On *2016-08-04 20:23:37 UTC*, **vw33** commented:

I have the same king of problems with reccurent events in v2.2.0.0.
How is it possible to get the new v2.2.2.1 that correct the problem?

**Comment by phw198** [comment]
On *2016-08-11 04:34:31 UTC*, **brozono** commented:

vw33

The hotfix executable is attached to this issue. See File Attachment section after the original problem description post.

**Comment by phw198** [comment]
On *2016-08-14 22:05:37 UTC*, **phw198** commented:

Fixed from v2.2.3

**Comment by phw198** [comment]
On *2016-08-16 00:35:53 UTC*, **brozono** commented:

For my learning were the the changes in Recurrence.cs for the new try/finally block in UpdateGoogleExceptions() and the addition of the finally in exceptionIsDeleted() the improved COM object de-references?

Thanks!

**Comment by Mumumurilo** [comment]
Hi, I'm using version 2.9.5.0 and I'm still having this error. Every time an exception is created by one of my colleagues the meeting is deleted from my Google Calendar.

The logs are reporting some errors:
```
2023-02-07 10:07:51,843 DEBUG  29 OutlookGoogleCalendarSync.Recurrence [601] -  12/01/2023 11:30 (R) => "PCW 2.0 - sync-up"
2023-02-07 10:07:51,845 DEBUG  29 OutlookGoogleCalendarSync.Recurrence [602] -  This is a recurring appointment with 4 exceptions that will now be iteratively compared.
2023-02-07 10:07:51,865 WARN  29 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance on 17/01/2023 has become inaccessible, probably due to caching
2023-02-07 10:07:51,867 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2023-02-07 10:07:51,873 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xAF604005,-1352646651; Location: get_AppointmentItem() in <Unknown File>
2023-02-07 10:07:51,889 WARN  29 OutlookGoogleCalendarSync.Recurrence [625] -  Exception is inaccessible and cannot be synced: 17/01/2023
2023-02-07 10:07:51,930 WARN  29 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance on 19/01/2023 has become inaccessible, probably due to caching
2023-02-07 10:07:51,933 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2023-02-07 10:07:51,934 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xBFE04005,-1075822587; Location: get_AppointmentItem() in <Unknown File>
2023-02-07 10:07:51,948 WARN  29 OutlookGoogleCalendarSync.Recurrence [625] -  Exception is inaccessible and cannot be synced: 19/01/2023
2023-02-07 10:07:51,987 WARN  29 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance on 06/02/2023 has become inaccessible, probably due to caching
2023-02-07 10:07:51,989 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2023-02-07 10:07:51,991 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xCE604005,-832552955; Location: get_AppointmentItem() in <Unknown File>
2023-02-07 10:07:52,005 WARN  29 OutlookGoogleCalendarSync.Recurrence [625] -  Exception is inaccessible and cannot be synced: 06/02/2023
2023-02-07 10:07:52,047 WARN  29 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance on 07/02/2023 has become inaccessible, probably due to caching
2023-02-07 10:07:52,050 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2023-02-07 10:07:52,052 FAIL  29 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xDEE04005,-555728891; Location: get_AppointmentItem() in <Unknown File>
2023-02-07 10:07:52,065 WARN  29 OutlookGoogleCalendarSync.Recurrence [625] -  Exception is inaccessible and cannot be synced: 07/02/2023
```

**Comment by phw198** [comment]
@Mumumurilo Please can you try the hotfix on #1593 - there are improvements around recurring series exception there.

**Comment by Mumumurilo** [comment]
@phw198 Just tried with the hotfix, but the error remains the same:

```
2023-02-23 09:25:59,389 DEBUG  28 OutlookGoogleCalendarSync.Recurrence [674] -  12/01/2023 11:00 (R) => "PCW 2.0 - sync-up"
2023-02-23 09:25:59,390 DEBUG  28 OutlookGoogleCalendarSync.Recurrence [675] -  This is a recurring appointment with 2 exceptions that will now be iteratively compared.
2023-02-23 09:25:59,398 WARN  28 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance on 20/02/2023 has become inaccessible, probably due to caching
2023-02-23 09:25:59,399 FAIL  28 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2023-02-23 09:25:59,400 FAIL  28 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x94904005,-1802485755; Location: get_AppointmentItem() in <Unknown File>
2023-02-23 09:25:59,408 WARN  28 OutlookGoogleCalendarSync.Recurrence [698] -  Exception is inaccessible and cannot be synced: 20/02/2023
2023-02-23 09:25:59,426 WARN  28 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance on 21/02/2023 has become inaccessible, probably due to caching
2023-02-23 09:25:59,428 FAIL  28 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2023-02-23 09:25:59,429 FAIL  28 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xA9304005,-1456455675; Location: get_AppointmentItem() in <Unknown File>
2023-02-23 09:25:59,434 WARN  28 OutlookGoogleCalendarSync.Recurrence [698] -  Exception is inaccessible and cannot be synced: 21/02/2023
2023-02-23 09:25:59,536 INFO  28 OutlookGoogleCalendarSync.Console [287] -  0 entries updated.
2023-02-23 09:26:00,399 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [148] -  Setting 'CompletedSyncs' updated to '2494'
2023-02-23 09:26:00,401 INFO  1 OutlookGoogleCalendarSync.Console [287] -  Sync finished!
```

**Comment by phw198** [comment]
And that's after fully closing down Outlook and OGCS (check task manager that Outlook.exe isn't still there), before restarting them both and syncing?
