### ISSUE TITLE
G->O: Unable to reclaim orphans after excluding corrupted item

### ISSUE THREAD

**Issue by inorv9** [phw198/OutlookGoogleCalendarSync#649]
**OGCS Version**: v2.7.7.1  
**Installed or Portable**: Installed

**Problem Description**  
I only want to sync one-way: Google to Outlook.
Seeing errors "unable to reclaim orphan calendar entries in Outlook" and "Object reference not set to an instance of an object". For example, now when I put in a manual calendar entry in Google it doesn't sync to Outlook.

**Steps to Reproduce the Issue**  
1. Occurs on every sync

**Any other information**  
Attached log, thank you

[OGcalsync.txt.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2730106/OGcalsync.txt.log)

**Comment by phw198** [comment]
:package: Please could you apply this [patch v2.7.7.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2752598/v2.7.7.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) which will add extra logging to try and narrow down what the problem is..

Please continue logging at `FINE` level and upload it again after trying a sync on v2.7.7.7.

**Comment by inorv9** [comment]
Friendly check-in on updated log file attached last week? thanks!

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.7.7.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2777069/v2.7.7.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please could you upload your logfile again once you've tried it. Thanks!

**Comment by inorv9** [comment]
Thanks, I am still getting the error but at the same time I think the google to outlook sync is working. I tried deleting all past and future meetings with "Hyperledger" but still get the error.

<img width="370" alt="untitled picture1" src="https://user-images.githubusercontent.com/34639028/51447214-3fa8a580-1d35-11e9-8479-33789bfbfe8a.png">

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2777209/OGcalsync.log)

**Comment by phw198** [comment]
OK, it has actually moved on further now, so I'll need to investigate what's tripping it up again...
