### ISSUE TITLE
Past recurring events duplication in Outlook Revisited

### ISSUE THREAD

**Issue by jjkober** [phw198/OutlookGoogleCalendarSync#823]
**OGCS Version**: v2.8.1.4
**Installed or Portable**: Installed

**Problem Description**  
Reference: https://github.com/phw198/OutlookGoogleCalendarSync/issues/799

The previous case is marked as "Resolved," so I am reopening this under a new case.

I have been traveling, but yesterday I went back to clean up some of the duplicated appointments for the "Jim/Steve…" event on ~~21-APR~~ (@phw198: I think you meant 26-APR), 10-MAY, 24-MAY, and 7-JUN. I deleted the series for each of the dozens of events, leaving the one valid appointment untouched on each date. This morning, I woke up and checked, and there were now four duplicate appointments on each of those dates. 

**Steps to Reproduce the Issue**  
I turned on fine debugging and synced again timemark: 2019-08-27 09:14:29. Now there are five duplicate appointments. Interestingly, no events have appeared on the 21-FEB date we were looking at in the original case #799 .

**Any other information**  
I emailed the log/csv files

**Comment by phw198** [comment]
Google recurring series for `Jim/Steve - Sales Rep Exec Sponsorship Bi-weekly Mtg.`:

| Start | Recurrence |
|---  |---|
|4/26/2019 3:00:00 PM|FREQ=WEEKLY;WKST=SU;UNTIL=20190621T065959Z;INTERVAL=2;BYDAY=FR|
|6/21/2019 3:00:00 PM|FREQ=WEEKLY;WKST=SU;UNTIL=20190830T065959Z;INTERVAL=2;BYDAY=FR|
|8/30/2019 3:00:00 PM||
|9/13/2019 3:00:00 PM||

The 1st one is the only one that spans 26-Apr, 10-May, 24-May 7-Jun.
However, you are syncing from 13-Aug to 26-Nov, so this series should no longer be in scope for sync (it has finished by 20-Jun). And if we check which series have been returned from Outlook, 26-Apr is not one of them....so why has it been returned for Google? This explains why it's getting created in Outlook every sync.

TBH, I think there must be something screwy with that series starting on the 26-Apr. Can you
1. delete it  entirely from Google
2. sync and check duplicates are no longer created in Outlook
3. recreate it manually in Google with exactly the same recurrence rule (every 2nd Friday until 20-Jun)
4. see if it still gets picked up in `google_events.csv` and synced to Outlook?

**Comment by phw198** [comment]
Really can't replicate this problem. I had wondered if an exception from the recurring series had been moved out into the period you are syncing, but Google still doesn't return this - the original series has to fall within the sync window.

I wonder if this is an odd feature of you having changed the username of your gmail account 3 times now. Perhaps we could try the below:
1. Create a new Google calendar in your account
1. Pick the 26-Apr recurring series and select "Duplicate to..." and select your new calendar
1. Create a new Outlook calendar folder
1. Find your `settings.xml` file and create a copy, eg `settings-823.xml`
1. In a CMD window, enter the following to start a new instance of OGCS running against that new settings file:
`C:\Users\<user-id>\AppData\Local\OutlookGoogleCalendarSync\app-2.8.1-alpha\OutlookGoogleCalendarSync.exe /s:C:\path-to\settings-823.xml /l:C:\path-to\OGcalsync-823.log`
1. Pick the new Google and Outlook calendar, save your settings.
1. Run a sync - check if the series has been synced.
1. Run another sync - has the series been duplicated?

**Comment by jjkober** [comment]
Okay, so I did that, ran it four times, and no dups.  So, why is my main calendar doing that for multiple series?  Emailing files.

**Comment by phw198** [comment]
So for the 26-Apr event you copied to "TestAccount", that recurrence rule looks to be `FREQ=WEEKLY;WKST=SU;INTERVAL=2;BYDAY=FR` - ie it has no end date, which would explain why OGCS is picking it up for sync.

Can you check what the recurrence configuration as taken from the Google event for both the original problematic item and the new duplicated one? Ie double click the event, and check what it says in the dropdown underneath the start/end dates. If it's "Custom" then maybe a screenshot of the config.

**Comment by jjkober** [comment]
They both say "Every 2 weeks on Friday"

**Comment by jjkober** [comment]
Only difference in my main account is that there are a few "exceptions" where they moved the date.

**Comment by jjkober** [comment]
...and now that I think about it, all the duplicating events had exceptions at one time or another.  Events that remained static are not duplicating.

**Comment by jjkober** [comment]
Case in point:  A static meeting that was fine, was not duplicating.  This week, they moved the meeting back a half hour for one day due to a conflict.  Now there are multiple duplicates for EVERY past event in that series.  Future events are not duplicated.

**Comment by jjkober** [comment]
I just synced my main account again and emailed the log files.  The event in question is "Fed - Current Customer Read Out" biweekly on Wednesdays at 7am PDT.  On 9/19/19 it was moved to 7:30am for one occurrence only.

**Comment by phw198** [comment]
So the recurrence rule as seen by OGCS for "Fed - Current Customer Read Out" is `FREQ=WEEKLY;WKST=SU;UNTIL=20190904T035959Z;INTERVAL=2;BYDAY=WE` - ie it has finished by 4-Sep and your sync window was from 8-Sep. 

So something's odd - are you saying the meeting occurrence was moved from 7am Wed 18th, to 7am Thurs 19th? Because there is no occurrence in Google on 18-Sep...!

Can you:
1. Open up the recurring series in the webview
1. Confirm the start data and time of the series
1. Click the recurrence drop down and then "Custom" and then screenshot the popup.
1. Append onto the URL `?eventdeb=1` and hit enter
1. Click "More Actions" > "Troubleshooting Info"
1. Provide the `eid` number, eg: `eid=0ue37d6442de1ge8fmj3uh3fgk`

**Comment by phw198** [comment]
FWIW, I can produce some kind of duplication, but it only creates 1 duplicate, and these are all in the past.

1. Create a recurring daily series starting on 20-Sep, ending on 28-Sep
1. Sync from 27-Sep to create in Outlook
1. Sync from 29-Sep - nothing happens
1. Edit the Google series to end on 1-Oct
1. Sync from 29-Sep - OGCS creates a new Outlook series, with events from the "original" series ending on 28-Sep duplicated.
1. Sync again from 29-Sep - no further changes.

This is a bug, but pretty low impact and not quite the one you're experiencing...

**Comment by jjkober** [comment]
There's actually more to the changes that may help explain:

1.  "Fed - Current Customer Read Out" was originally every Wednesday at 7am.  
2.   On 15-Aug, the owner moved it to Thursday at 7am for one occurrence. 
3.   On 4-Sep, the owner changed the name to "Public Sector - Current Customer Read Out"  
3.   Then on 18-Sep he moved it to 7:30am for one occurrence.
4.   I declined 2-Oct because I am leaving for holiday for two weeks starting tomorrow.
5.   The meeting "Public Sector - Current Customer Read Out"  resumes on 16-Oct at 7am, and every other Wednesday thereafter.
6.   Even though there is no more "Fed - Current Customer Read Out" event, and I'm only syncing two weeks back, I am still seeing duplicates created in Outlook every other Wednesday from 10-Jul to 21-Aug.  There are no dups before or after that date range.
7.   I tried performing the tasks you requested above, but I do not have change access to the meeting, so I am unable to alter the recurrence drop down and I do not see "Troubleshooting Info" under "More Actions." 
8.   I am not intentionally trying to drive you mad...

Here is some more "interesting" info -- see the attached screenshot where I searched Google for "current customer read out."  
> The first event is on July 10, (Fed) which shows in Google and duplicates in outlook.  
> 24-Jul (Fed) is in Google and duplicates in Outlook
> 15-Aug (Fed & Thursday) is in Google , but does NOT appear in Outlook
> 21-Aug (Fed) is NOT in Google , but duplicates in Outlook
> On 4-Sep when it changes,to Public Sector, all is fine thereafter.
>  I fear that if an occurrence changes in Public Sector, the same duplication will start again.

![image](https://user-images.githubusercontent.com/31284808/65841866-cefe5380-e2db-11e9-994c-4d1cfe6aa24a.png)

Is there anything else you would like me to try before I leave for two weeks?  I could delete the old series in Google and see if everything goes away, but that wouldn't solve the longer-term issue. Perhaps I should try syncing "0 days in the past?"

**Comment by phw198** [comment]
Given #799 was (partly) fixed by sorting out the end date of a recurring series, there was actually a bug in this just fixed on #889.

Could you apply the hotfix on #889, manually delete the duplicates you have in Outlook and then see if OGCS still re-introduces duplicates?

**Comment by jjkober** [comment]
Sadly, that did not fix the problem.  I deleted all the duplicate instances of the four duplicating appointments, verified that I was running 2.8.2.4, ran OGCS twice, and all four were duplicated.

I am emailing the logs and here is a list of the four dates/appts that are duplicating still.

![image](https://user-images.githubusercontent.com/31284808/68547554-c3508300-0397-11ea-8b71-7ae99a2c0bee.png)

**Comment by jjkober** [comment]
On a side note, I also tried deleting EVERY instance of those four meetings and running OGCS a couple of times, and I achieved the same dup result.

**Comment by phw198** [comment]
@jjkober Not sure if you still use OGCS, but I'm doing a bit of a spring clean-up - any problem if I close this given it's so old?

**Comment by jjkober** [comment]
Go ahead and close it. I just live off of Google Calendar these days. Thanks!

 

-jjk

**Comment by phw198** [comment]
Thanks for the quick response!
