### ISSUE TITLE
Meetings created in UTC time are not synched correctly

### ISSUE THREAD

**Issue by MartinJJ** [phw198/OutlookGoogleCalendarSync#970]
**OGCS Version**: 2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  

Hello OGCS,

When meetings in other global sites are made in 'their' timezone the subsequent synchronisation from Outlook to Google Calender 
works fine. The local time is correctly reflected in the OGCS Synchronisation.
Now, more and more, users in USA are starting to set meetings in UTC time, i.o. their local zone
in their Outlook calendar. Thee are correctly displayed in our European Outlook with our local timezone.
However, these meetings are the NOT correctly synchronised to Google calendar.

See the example below:

The example Meeting is created          Austin in USA: CDT and with DST at UTC -5
is correclty shown in my timezone in The Netherlands : CET No DST yet   at UTC +1
Then this meeting in my Outlook is synchronised to Google calendar with an extra 5 hour added.
Do you have any idea what causes this and if OGCS could be corrected to treat UTC meeting correctly ?

Running OGCS: 
   Version	2.8.0.0
   Timezone DB 2019c

Regards, Martin 

'SyncTeam Standup' Meeting:
In last week it was shifted around in time, also due to DST start in USA.
The it was recreated in UTC time, at 14:00 in Europe and since, it;s being synchronised to 19:00 to Google calendar

Created         in Outlook         in Austin   USA: UTC -5 (With DST)   :: 13:00 - 13:28 UTC  (Local time: 09:00 - 09:28 CDT)
---
Shown correct   in Outlook         in Eindhoven NL: UTC +1 (NO DST yet) :: 14:00 - 14:28 CET
Shown InCorrect in Google Calendar in Eindhoven NL: UTC +1 (NO DST yet) :: 19:00 - 19:28 CET after update by OGCS from Outlook

Somehow  OGCS adds another  5 hours...

NL: The Netherlands

  DST : Dailight Saving Time
  
  CDT : Central Daylight Time   Central USA - With DST
  CET : Central European Time  Central Europe Time -Without DST
---

**Steps to Reproduce the Issue**  
1. Create meeting in UTC, preferably 
  by   someone else from a Outlook setup in another timezone !
2. In your own timezone accept the meeting
2. sync to Google via OGCS 
   check local time update e.g. with help of  https://www.timeanddate.com/worldclock/
3. Check time in your Google calendar

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4381657/OGcalsync.log)

**Comment by phw198** [comment]
Hi @MartinJJ 

This is a shame! You're one of the few people to go to the trouble of documenting the issue and how to reproduce it...but haven't followed the guidance of upgrading to latest release first! This should be fixed in v2.8.3 :wink:

**Comment by MartinJJ** [comment]
Hello Paul,

Thanks for checking this and sorry i didn't check with a  -alpha version.
I did th 'Check for updates' from v2.8.0 and found none, but skipped the -alpha update option.

Today I installed the v2.8.3-alpha, saw the  UTC item being mentioned in the fixes, ran the Sync a few times...
However the 'SyncTeam Standup' meeting on Monday and Thursday is still in the evening in the Google Calendar.
 Now at 20:00 - 20:28  i.o 19:00 - 19:28 due to Europe going to DST  (CEST)).

Added the latest .log and a screenshot of the meeting in Google.
Hope you can help debugging this.

Regards, Martin

![Screen Shot 2020-04-06-09 16 30](https://user-images.githubusercontent.com/3940571/78532551-bec5b480-77e7-11ea-8344-7aa27b87a76b.JPG)



[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4436425/OGcalsync.log)

**Comment by MartinJJ** [comment]
Hi OGCS,

Issue is 'open' but no longer assigned as labelled 'old release'.
Since first info I tested with latest alpha version and the issue persists.
See details above.
Can you look into it as I get annoying meetings in my calendar late in the evening that really are scheduled for the early afternoon..

Regards, Martin

**Comment by phw198** [comment]
Hi @MartinJJ 

I'd suggest you run a full sync by pressing `Shift` and clicking `Sync` - this should ensure the right timezone is set for your Google events. Let me know if that helps.

If not please set logging to `FINE`, run another Full Sync and then upload your logs again.

**Comment by MartinJJ** [comment]
Hi Paul,

Did as suggested,  Shift Sync : Full Sync:   still same issue.
Attached the log from after the Full Sync withe logging set to FINE,
and screenshots of the  Outlook and Google meetings

Hope you can find the issue,

Regards, Martin

[OGcalsync_FINE_AfterFullSync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4598320/OGcalsync_FINE_AfterFullSync.log)

![Meeting_Outlook](https://user-images.githubusercontent.com/3940571/81394707-ab797200-9122-11ea-9fa4-05ebd58fa2c3.jpg)
![Meeting_Google](https://user-images.githubusercontent.com/3940571/81394722-b207e980-9122-11ea-90b0-5f5d866cce1d.jpg)

**Comment by phw198** [comment]
I would say those other users in the US sending invites in UTC have got their calendars/environments misconfigured. Organisers should be sending invites from their own timezone...
```
2020-05-08 11:58:42,910 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Meeting organiser is someone else - checking their timezone.
2020-05-08 11:58:42,945 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Appointment's timezone: (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
2020-05-08 11:58:42,946 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Organiser's timezone:   (UTC) Coordinated Universal Time
2020-05-08 11:58:42,946 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Retrieving the meeting organiser's timezone ID.
2020-05-08 11:58:42,947 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Timezone "(UTC) Coordinated Universal Time" mapped to "Etc/UTC"
```
Other appointments will say, for example:
```
2020-05-08 11:58:43,320 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Meeting organiser is someone else - checking their timezone.
2020-05-08 11:58:43,354 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Timezone "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" mapped to "Europe/Berlin"
```
which is properly configured.
Has something changed with the setup of the organisers in "UTC"? Exchange environment? O365?

**Comment by MartinJJ** [comment]
Hi Paul,
As the initial post and title mention: they started to explicitly create recurring meetings in UTC.
To 'avoid' having to change them during Daylight Saving Time changes in US and later again in Europe, etc...
This way a meeting 'only' changes at the location where DST is set or unset.
So creation is done on purpose in UTC.
Outlook shows them correctly. 
    See the Outlook screenshot, also showing the info on the original Timezone: UTC.
OGCS now 'moves' them in time, incorrectly.
Would be great if OGCS could also support this use-case, and set the meeting to the correct local time.

Regards, Martin

**Comment by phw198** [comment]
> This way a meeting 'only' changes at the location where DST is set or unset.

This really doesn't make any sense to me. What are they trying to avoid?? Do they know that Outlook actually stores all calendar dates as UTC internally anyway and that is then converted to local timezones for each attendee when it's displayed? Outlook will automatically work out the timezone and correct appointment time for each recipient. DST included.

But persevering with this, I think the steps to reproduce are:
1. Create Outlook appointment in Eastern Time (UTC-4) at 09:00 recurring bi-weekly from 4-Feb-2020 from an organiser in Eastern Time zone.
1. **This is stored as 14:00 UTC within Outlook and sender timezone of Eastern Time**
    1. Outlook shows as 14:00 for me in GMT (UTC+0), changing to 13:00 BST (UTC+1) for 13-Mar, and back to 14:00 BST (UTC+1) on 31-Mar.
    1. What do you know, Outlook has automatically worked out that the US changes their clocks on a different week to Europe, and handled that automatically!
1. Sync all this to Google OK - is **not** stored in UTC, but Eastern Time (sender's timezone).
1. Now have the organiser change the Outlook appointment to be in UTC and starting at 14:00.
    1. **This is stored as 14:00 UTC within Outlook and sender timezone of UTC**
    1. Outlook will show this as before, as the internal storage of meeting time is **the same**.
    1. OGCS will now see no change in start time, but it WILL see a change in timezone - 4 hours later. This will get synced to Google, and what do you know, it's showing 4 hours late.

This is not something to be fixed in OGCS - as far as I can tell it's a PEBKAC, they need to stop pretending their meeting organisers are in UTC when they are not.

To work around it though, have you tried setting OGCS to one way (O->G), deleting the series in Google and letting OGCS recreate it? This should mean it calculates the Google start time and timezone afresh and then hopefully show correctly...

Also note, if that does work, this will only affect recurring meetings that were created by non-UTC organisers before they were teleported to UTC.

**Comment by MartinJJ** [comment]
Hello Paul,

OK, I wasn't clear in why we create meetings in UTC.
We are a global company with branches in many States and Countries in America (North and South), Europe and Asia.
Every State and Country changes to-, and from DST at other days, often weeks apart.
Outlook perfectly sets the meetings to the local day and time, from whatever Timezone they are created.
As you show in your example.
However, many meetings of average one hour at least, mostly occur    right after each other, because we have a small time window to all meet.
But they originate from different time zones and so get split apart and worse, start to overlap during local DST changes.
Then people start moving some meetings to 'best fit all' which is not easy, and then the next State or Country changes DST....
Until everybody is on-, or off DST. And it all restarts half a year later...
When we create all these meetings in UTC, they shift a bit over the day when a site changes DST, but all meetings then nicely keep allined.

The time window on a day where people from AMEC, EMEA, and APAC, can all join is very limited, and always some have to work, very, early, and some rather late on some days to be able to all meet.

When local DST changes this mixes it all up for a few weeks and this becomes messy.
When all are created in UTC, at least they all align locally for everyone, even with an hour's change a few times a year.

Hope this explains the reason for Creating meetings in UTC.

I am only synching O->G now and tried to delete in G an resync some time ago without solving the issue. That might have been in the non-alpha version.
I'll retry when I am on my work laptop again.

Regards, Martin

**Comment by phw198** [comment]
OK, that does make some kind of sense - you're trying to avoid the confusion in the 8-9:00 GMT window that works for most global teams, during the couple of weeks where different countries observe DST on different dates. Thanks for explaining!

Let's see what happens when you let OGCS create these Google events from scratch...

**Comment by MartinJJ** [comment]
Hello Paul,

 Nope... didn't work.
Removed the meeting series at Google.  Did a  Shift: Full Sync
and the series was recreated at 22:00

OGCS screen attached:

![Screen Shot 2020-05-11-10 13 33](https://user-images.githubusercontent.com/3940571/81539426-7e220380-9370-11ea-8955-edc5013c4fd9.JPG)


Regards, Martin

**Comment by phw198** [comment]
I'd need to see the `FINE` level logs for that creation. Also if you are able to export the `.ics` file from Outlook for that particular invite (you can obfuscate the email addresses etc) and sent that over that would be a big help.

**Comment by MartinJJ** [comment]
Hi Paul,

Deleted, and Re-Created with FINE logging
attached  is the log file  and the (bit redacted) .ics file of the meeting.
 (Renamed to  ..._.txt to be able to attach it).

Regards, Martin

[OGcalsync_FINE_After_Del.and.ReCreateMeeting.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4608846/OGcalsync_FINE_After_Del.and.ReCreateMeeting.log)
[11 Don+Martin.ics_.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4608848/11.Don%2BMartin.ics_.txt)

**Comment by phw198** [comment]
I think you're in a pretty unique situation whereby meeting organisers look to be situated in the UTC timezone when they are in fact not. 

I'm therefore hesitant to offer a solution, but in spite of this please try the following:
1. Apply below hotfix
1. Open OGCS, go to Settings and hit `Save`
1. Go to About and double click the "Config In" path value to open Windows Explorer
1. Close OGCS
1. In Windows Explorer edit `settings.xml` and change the line to `true`
`<DisregardOrganiserTimezone>true</DisregardOrganiserTimezone>`
1. Start OGCS and perform a full sync / manually delete appointment and have OGCS recreate it.

:package: [Hotfix v2.8.3.17.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4776395/v2.8.3.17.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes!

**Comment by MartinJJ** [comment]
Hi Paul,

Thanks!
Will do, and keep you updated.

Met vriendelijke  groet, Kind regards,  Martin

Op zo 14 jun. 2020 14:40 schreef Paul Woolcock <notifications@github.com>:

**Comment by MartinJJ** [comment]
Hi Paul,

Did as requested,  didn't help.
Newly created meetings remain at 19:00  CEST...

Last run, with 'Ctrl Sync'  and debug level at FINE

Regards, Martin

----

From the log (attached): `Program started: v2.8.3.0`   ??
Where the About Tab info shows: Version	2.8.3.17
So should be OK

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4778825/OGcalsync.log)

**settings info**
 Logging level configured to 'Fine'
 DisregardOrganiserTimezone: True

"SyncTeam Standup" : Should be in CEST at 15:00 (OK in Outlook)
Initially created in UTC
Starts 2020-03-23 14:00 - 14:28  (Then  CET, so now  15:00 CEST)

**Shows in OGCS as**

2020-03-23 19:00 (R) => "SyncTeam Standup"
This is a recurring appointment with 21 exceptions that will now be iteratively compared.

**Comment by phw198** [comment]
Thanks @MartinJJ....but I think that's bad news.

Firstly, the start of the log for v2.8.3.0 is just because that before you applied the hotfix, so OK. After you've applied the hotfix the issue is:

Outlook internally has the appointment time at 19:00 which normally has a timezone against it to correct the offset*. I think if the meeting was organised by an East coast American UTC-5, that would normally make it 14:00 and then any adjustment for you in CEST to 15:00.

Problem is, because there's this fakery in your organisation of all organisers being in "UTC", there's no offset to apply - and Outlook doesn't store anywhere (that's programmatically available*) that the organiser is actually UTC-5. I'm afraid this one is a "can't fix" issue.

\* Outlook doesn't even store the organiser's timezone properly anyway - it stores it somewhere internally and inaccessible and calculates the local time for the recipient upon receipt (which is why Outlook shows it correctly). But the organiser's timezone is just held as a string in Outlook (which is why I had to add the timezone mapping feature!) and for you this is showing UTC, not UTC-5.

**Comment by MartinJJ** [comment]
Hi Paul,

 Thanks for the investigation time, pitty it cannot be helped but understand why.
 Still  happy with OGCS  :-)

Regards, Martin
